### ISSUE TITLE
Fix the link of AdGuard Home

### ISSUE THREAD

**Issue by Chinaski1** [PeterDaveHello/nrd-list-downloader#1]
At [readme.md](https://github.com/PeterDaveHello/nrd-list-downloader#readme) the link of AdGuard Home goes to https://pi-hole.net/
Please fix it to https://github.com/AdguardTeam/Adguardhome

**Comment by PeterDaveHello** [comment]
@Chinaski1 nice catch! Would you like to send a pull request for it? Thanks!
